# Generated by Django 5.2.4 on 2025-08-22 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='User who has claimed this startup as their company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_startups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startup',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='startups.industry'),
        ),
        migrations.AddField(
            model_name='startup',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_startups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupbookmark',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startupbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupclaimrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claim_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupclaimrequest',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startupclaimrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_claim_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupcomment',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startupcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupeditrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_edit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupeditrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupeditrequest',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startupfounder',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startuplike',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startuplike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startuprating',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startuprating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startupsubmission',
            name='startup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='startupsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='startuptag',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['is_approved', 'is_featured'], name='startups_st_is_appr_80fd95_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['industry', 'is_approved'], name='startups_st_industr_7f011e_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['location', 'is_approved'], name='startups_st_locatio_5f06e2_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['created_at'], name='startups_st_created_93e688_idx'),
        ),
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['is_claimed', 'claim_verified'], name='startups_st_claimed_idx'),
        ),
        migrations.AddIndex(
            model_name='startupbookmark',
            index=models.Index(fields=['user', 'created_at'], name='startups_st_user_id_92c6b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='startupbookmark',
            unique_together={('startup', 'user')},
        ),
        migrations.AddIndex(
            model_name='startupclaimrequest',
            index=models.Index(fields=['status', 'created_at'], name='startups_st_status_da0ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='startupclaimrequest',
            index=models.Index(fields=['startup', 'status'], name='startups_st_startup_7afb57_idx'),
        ),
        migrations.AddIndex(
            model_name='startupclaimrequest',
            index=models.Index(fields=['user', 'created_at'], name='startups_st_user_id_5fef9d_idx'),
        ),
        migrations.AddIndex(
            model_name='startupclaimrequest',
            index=models.Index(fields=['verification_token'], name='startups_st_verific_6a800f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='startupclaimrequest',
            unique_together={('startup', 'user')},
        ),
        migrations.AddIndex(
            model_name='startupcomment',
            index=models.Index(fields=['startup', 'created_at'], name='startups_st_startup_6fb60b_idx'),
        ),
        migrations.AddIndex(
            model_name='startupcomment',
            index=models.Index(fields=['user', 'created_at'], name='startups_st_user_id_00fb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='startupeditrequest',
            index=models.Index(fields=['status', 'created_at'], name='startups_st_status_d7c77c_idx'),
        ),
        migrations.AddIndex(
            model_name='startupeditrequest',
            index=models.Index(fields=['startup', 'status'], name='startups_st_startup_05c13e_idx'),
        ),
        migrations.AddIndex(
            model_name='startupeditrequest',
            index=models.Index(fields=['requested_by', 'created_at'], name='startups_st_request_952f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='startuplike',
            index=models.Index(fields=['startup', 'created_at'], name='startups_st_startup_618547_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='startuplike',
            unique_together={('startup', 'user')},
        ),
        migrations.AddIndex(
            model_name='startuprating',
            index=models.Index(fields=['startup', 'created_at'], name='startups_st_startup_4e8f79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='startuprating',
            unique_together={('startup', 'user')},
        ),
        migrations.AddIndex(
            model_name='startupsubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='startups_st_status_594e10_idx'),
        ),
        migrations.AddIndex(
            model_name='startupsubmission',
            index=models.Index(fields=['submitted_by', 'submitted_at'], name='startups_st_submitt_ce1579_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='startuptag',
            unique_together={('startup', 'tag')},
        ),
    ]
