{
  "services": [
    {
      "type": "web",
      "name": "startup-hub-backend",
      "env": "python",
      "plan": "starter",
      "buildCommand": "pip install -r requirements.txt && python manage.py collectstatic --noinput",
      "startCommand": "gunicorn startup_hub.wsgi:application",
      "envVars": [
        {
          "key": "PYTHON_VERSION",
          "value": "3.11"
        },
        {
          "key": "DJANGO_SETTINGS_MODULE",
          "value": "startup_hub.settings.production"
        },
        {
          "key": "SECRET_KEY",
          "generateValue": true
        },
        {
          "key": "DEBUG",
          "value": "False"
        },
        {
          "key": "ALLOWED_HOSTS",
          "value": ".onrender.com"
        },
        {
          "key": "DATABASE_URL",
          "fromService": {
            "type": "pserv",
            "name": "startup-hub-db"
          }
        }
      ]
    },
    {
      "type": "pserv",
      "name": "startup-hub-db",
      "env": "postgresql",
      "plan": "starter"
    }
  ]
}