# Generated by Django 5.2.4 on 2025-08-22 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='blocked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_card', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsignal',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsignal',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='related_job_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_settings', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='messaging.event'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.message'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageread',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='messageread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='messaging.poll'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='messaging.polloption'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_poll_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedbusinesscard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='messaging.businesscard'),
        ),
        migrations.AddField(
            model_name='sharedbusinesscard',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_cards', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='sharedbusinesscard',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_cards', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='sharedbusinesscard',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedbusinesscard',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userconnection',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userconnection',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocall',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocall',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='videocall',
            name='participants',
            field=models.ManyToManyField(related_name='video_calls', through='messaging.CallParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='related_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.videocall'),
        ),
        migrations.AddField(
            model_name='callsignal',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='messaging.videocall'),
        ),
        migrations.AddField(
            model_name='callparticipant',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_participants', to='messaging.videocall'),
        ),
        migrations.AddIndex(
            model_name='blockeduser',
            index=models.Index(fields=['user', 'blocked_user'], name='messaging_b_user_id_b08a98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockeduser',
            unique_together={('user', 'blocked_user')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='messaging_c_updated_666ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrequest',
            index=models.Index(fields=['to_user', 'status', '-sent_at'], name='messaging_c_to_user_11adc1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrequest',
            index=models.Index(fields=['from_user', '-sent_at'], name='messaging_c_from_us_a1d459_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatrequest',
            unique_together={('from_user', 'to_user')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['conversation', 'starts_at'], name='messaging_e_convers_f47662_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', '-created_at'], name='messaging_e_created_7b569a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['event', 'status'], name='messaging_e_event_i_3568fa_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['user', '-responded_at'], name='messaging_e_user_id_db39b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user', '-joined_at'], name='messaging_c_user_id_c59ae0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message', 'emoji'], name='messaging_m_message_5250bc_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['user', '-created_at'], name='messaging_m_user_id_53f481_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='messageread',
            index=models.Index(fields=['user', '-read_at'], name='messaging_m_user_id_199543_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageread',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['conversation', '-created_at'], name='messaging_p_convers_2677f4_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['created_by', '-created_at'], name='messaging_p_created_cb14b4_idx'),
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['poll', 'order'], name='messaging_p_poll_id_04ba45_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['option', 'user'], name='messaging_p_option__fe8901_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['user', '-voted_at'], name='messaging_p_user_id_b52f62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together={('option', 'user')},
        ),
        migrations.AddIndex(
            model_name='sharedbusinesscard',
            index=models.Index(fields=['shared_with', '-shared_at'], name='messaging_s_shared__3b5dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedbusinesscard',
            index=models.Index(fields=['shared_by', '-shared_at'], name='messaging_s_shared__176f9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sharedbusinesscard',
            unique_together={('card', 'shared_with', 'conversation')},
        ),
        migrations.AddIndex(
            model_name='userconnection',
            index=models.Index(fields=['from_user', '-connected_at'], name='messaging_u_from_us_54a4ba_idx'),
        ),
        migrations.AddIndex(
            model_name='userconnection',
            index=models.Index(fields=['to_user', '-connected_at'], name='messaging_u_to_user_8b8fd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userconnection',
            unique_together={('from_user', 'to_user')},
        ),
        migrations.AddIndex(
            model_name='videocall',
            index=models.Index(fields=['conversation', '-created_at'], name='messaging_v_convers_6bf8a4_idx'),
        ),
        migrations.AddIndex(
            model_name='videocall',
            index=models.Index(fields=['caller', '-created_at'], name='messaging_v_caller__8fe093_idx'),
        ),
        migrations.AddIndex(
            model_name='videocall',
            index=models.Index(fields=['status', '-created_at'], name='messaging_v_status_bf7f33_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'sent_at'], name='messaging_m_convers_118d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-sent_at'], name='messaging_m_sender__6eab7d_idx'),
        ),
        migrations.AddIndex(
            model_name='callsignal',
            index=models.Index(fields=['call', 'signal_type', '-created_at'], name='messaging_c_call_id_3501d6_idx'),
        ),
        migrations.AddIndex(
            model_name='callsignal',
            index=models.Index(fields=['to_user', 'processed', '-created_at'], name='messaging_c_to_user_e1eb46_idx'),
        ),
        migrations.AddIndex(
            model_name='callparticipant',
            index=models.Index(fields=['call', 'status'], name='messaging_c_call_id_3b8545_idx'),
        ),
        migrations.AddIndex(
            model_name='callparticipant',
            index=models.Index(fields=['user', '-invited_at'], name='messaging_c_user_id_975f39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='callparticipant',
            unique_together={('call', 'user')},
        ),
    ]
