# Generated by Django 5.2.4 on 2025-08-22 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('startups', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='startups.industry'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='selected_resume',
            field=models.ForeignKey(blank=True, help_text="Resume selected from user's saved resumes", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='users.resume'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='jobbookmark',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobeditrequest',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobeditrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_edit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobeditrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_job_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobshare',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobshare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_templates', to='startups.startup'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobtype'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobtype'),
        ),
        migrations.AddField(
            model_name='jobview',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_views', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status', 'applied_at'], name='jobs_jobapp_status_6642d6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'status'], name='jobs_jobapp_user_id_149a27_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='jobs_jobapp_job_id_08192b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'user')},
        ),
        migrations.AddIndex(
            model_name='applicationnote',
            index=models.Index(fields=['application', 'created_at'], name='jobs_applic_applica_fe733b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobbookmark',
            index=models.Index(fields=['user', 'created_at'], name='jobs_jobboo_user_id_d9a445_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobbookmark',
            unique_together={('job', 'user')},
        ),
        migrations.AddIndex(
            model_name='jobeditrequest',
            index=models.Index(fields=['status', 'created_at'], name='jobs_jobedi_status_a5210c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobeditrequest',
            index=models.Index(fields=['job', 'status'], name='jobs_jobedi_job_id_1142c8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobshare',
            index=models.Index(fields=['job', 'shared_at'], name='jobs_jobsha_job_id_b973ea_idx'),
        ),
        migrations.AddIndex(
            model_name='jobskill',
            index=models.Index(fields=['skill'], name='jobs_jobski_skill_a6f1bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobskill',
            unique_together={('job', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='jobtemplate',
            unique_together={('startup', 'name')},
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['user', 'is_active'], name='jobs_jobale_user_id_82ec0d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['frequency', 'is_active'], name='jobs_jobale_frequen_7e5ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_at'], name='jobs_job_posted__7edcdf_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'status'], name='jobs_job_is_acti_74c18c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['startup', 'is_active'], name='jobs_job_startup_df8fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'posted_at'], name='jobs_job_status_60011a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_by', 'status'], name='jobs_job_posted__f94b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['job', 'viewed_at'], name='jobs_jobvie_job_id_d75b29_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['user', 'viewed_at'], name='jobs_jobvie_user_id_41593d_idx'),
        ),
    ]
