# Generated by Django 4.2.23 on 2025-09-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_email',
            field=models.EmailField(blank=True, help_text='Company contact email (optional)', max_length=254),
        ),
    ]
