# Generated by Django 4.2.23 on 2025-09-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_fix_company_email_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_link',
            field=models.URLField(blank=True, help_text='External application link for the job', max_length=500),
        ),
    ]
