# Generated by Django 4.2.23 on 2025-07-29 15:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('harassment', 'Harassment or Bullying'), ('spam', 'Spam or Unwanted Content'), ('inappropriate_content', 'Inappropriate Content'), ('fake_profile', 'Fake Profile'), ('impersonation', 'Impersonation'), ('intellectual_property', 'Intellectual Property Violation'), ('privacy_violation', 'Privacy Violation'), ('scam', 'Scam or Fraud'), ('hate_speech', 'Hate Speech'), ('other', 'Other')], help_text='Category of the report', max_length=50)),
                ('reason', models.TextField(help_text='Detailed explanation of the issue (minimum 10 characters)', validators=[django.core.validators.MinLengthValidator(10)])),
                ('evidence_urls', models.JSONField(blank=True, default=list, help_text='URLs to screenshots or other evidence')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], default='pending', help_text='Current status of the report', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level assigned by admin', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use only')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the report was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the report was modified')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the report was resolved', null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, help_text='Admin user assigned to handle this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(help_text='User being reported', on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='User who submitted the report', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date these statistics are for')),
                ('total_reports', models.IntegerField(default=0, help_text='Total reports created on this date')),
                ('pending_reports', models.IntegerField(default=0, help_text='Reports in pending status')),
                ('resolved_reports', models.IntegerField(default=0, help_text='Reports resolved on this date')),
                ('avg_response_time_hours', models.FloatField(blank=True, help_text='Average response time in hours', null=True)),
                ('report_type_breakdown', models.JSONField(default=dict, help_text='Count of reports by type')),
                ('priority_breakdown', models.JSONField(default=dict, help_text='Count of reports by priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='reports_rep_date_f06b94_idx')],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='ReportAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('status_change', 'Status Changed'), ('priority_change', 'Priority Changed'), ('assignment_change', 'Assignment Changed'), ('note_added', 'Note Added'), ('user_warned', 'User Warned'), ('user_suspended', 'User Suspended'), ('user_banned', 'User Banned'), ('content_removed', 'Content Removed'), ('profile_restricted', 'Profile Restricted'), ('report_escalated', 'Report Escalated'), ('evidence_added', 'Evidence Added'), ('other', 'Other Action')], help_text='Type of action performed', max_length=30)),
                ('description', models.TextField(help_text='Detailed description of the action taken')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data related to the action (old/new values, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this action was performed')),
                ('admin', models.ForeignKey(help_text='Admin who performed this action', on_delete=django.db.models.deletion.CASCADE, related_name='report_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(help_text='The report this action is related to', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='reports.userreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['status', 'priority'], name='reports_use_status_6dd266_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reported_user', 'created_at'], name='reports_use_reporte_398652_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reporter', 'created_at'], name='reports_use_reporte_b70008_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['assigned_admin', 'status'], name='reports_use_assigne_480a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportaction',
            index=models.Index(fields=['report', 'created_at'], name='reports_rep_report__3c502f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportaction',
            index=models.Index(fields=['admin', 'created_at'], name='reports_rep_admin_i_aa2bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportaction',
            index=models.Index(fields=['action_type', 'created_at'], name='reports_rep_action__802302_idx'),
        ),
    ]
