# Generated by Django 4.2.23 on 2025-07-30 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_alter_postlink_options_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('spam', 'Spam or Unwanted Content'), ('harassment', 'Harassment or Bullying'), ('inappropriate_content', 'Inappropriate Content'), ('misinformation', 'Misinformation or False Information'), ('hate_speech', 'Hate Speech'), ('violence', 'Violence or Harmful Content'), ('nudity', 'Nudity or Sexual Content'), ('intellectual_property', 'Intellectual Property Violation'), ('privacy_violation', 'Privacy Violation'), ('scam', 'Scam or Fraud'), ('off_topic', 'Off-topic or Irrelevant'), ('duplicate', 'Duplicate Content'), ('other', 'Other')], help_text='Category of the report', max_length=50)),
                ('reason', models.TextField(help_text='Detailed explanation of the issue')),
                ('additional_context', models.TextField(blank=True, help_text='Additional context or information')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], default='pending', help_text='Current status of the report', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level assigned by admin', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use only')),
                ('action_taken', models.CharField(blank=True, help_text='Action taken by admin (e.g., post removed, user warned)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the report was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the report was modified')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the report was resolved', null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, help_text='Admin user assigned to handle this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_post_reports', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(help_text='Post being reported', on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to='posts.post')),
                ('reporter', models.ForeignKey(help_text='User who submitted the report', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_post_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='reports_pos_status_f8143e_idx'), models.Index(fields=['post', 'created_at'], name='reports_pos_post_id_3decb8_idx'), models.Index(fields=['reporter', 'created_at'], name='reports_pos_reporte_53e504_idx'), models.Index(fields=['assigned_admin', 'status'], name='reports_pos_assigne_59bd2b_idx')],
                'unique_together': {('reporter', 'post')},
            },
        ),
    ]
