# Generated by Django 4.2.23 on 2025-07-30 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_postreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Warning message sent to the user')),
                ('reason', models.TextField(help_text='Admin reason for the warning')),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_warnings', to=settings.AUTH_USER_MODEL)),
                ('post_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='reports.postreport')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='reports.userreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='reports_use_user_id_0dcc06_idx'), models.Index(fields=['admin', '-created_at'], name='reports_use_admin_i_a088a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_type', models.CharField(choices=[('temporary', 'Temporary Ban'), ('permanent', 'Permanent Ban')], max_length=20)),
                ('reason', models.TextField(help_text='Admin reason for the ban')),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Duration in days for temporary bans', null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lift_reason', models.TextField(blank=True, help_text='Reason for lifting the ban early')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_bans', to=settings.AUTH_USER_MODEL)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_bans', to=settings.AUTH_USER_MODEL)),
                ('post_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans', to='reports.postreport')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans', to='reports.userreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='reports_use_user_id_201c3f_idx'), models.Index(fields=['admin', '-created_at'], name='reports_use_admin_i_0c9ecd_idx'), models.Index(fields=['expires_at'], name='reports_use_expires_54e67e_idx')],
            },
        ),
    ]
