# Generated by Django 5.2.1 on 2025-07-19 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('system', 'System')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['webm', 'opus', 'ogg', 'mp3', 'wav'])]),
        ),
    ]
