# Generated by Django 5.2.1 on 2025-07-21 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_selected_resume'),
        ('messaging', '0005_message_message_type_message_voice_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('general', 'General'), ('job_application', 'Job Application'), ('investor', 'Investor Interest'), ('mentorship', 'Mentorship')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='related_job_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='jobs.jobapplication'),
        ),
    ]
