# Generated by Django 5.2.1 on 2025-07-21 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_conversation_conversation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('system', 'System'), ('call', 'Call')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('left', 'Left'), ('declined', 'Declined'), ('disconnected', 'Disconnected')], default='invited', max_length=20)),
                ('peer_id', models.CharField(blank=True, max_length=100)),
                ('is_video_enabled', models.BooleanField(default=True)),
                ('is_audio_enabled', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_type', models.CharField(choices=[('video', 'Video Call'), ('audio', 'Audio Call')], default='video', max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('answered', 'Answered'), ('ended', 'Ended'), ('missed', 'Missed'), ('declined', 'Declined'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('room_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 rating for call quality', null=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls', to='messaging.conversation')),
                ('participants', models.ManyToManyField(related_name='video_calls', through='messaging.CallParticipant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('ice-candidate', 'ICE Candidate'), ('call-end', 'Call End')], max_length=20)),
                ('signal_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='messaging.videocall')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='callparticipant',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_participants', to='messaging.videocall'),
        ),
        migrations.AddField(
            model_name='message',
            name='related_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.videocall'),
        ),
        migrations.AddIndex(
            model_name='videocall',
            index=models.Index(fields=['conversation', '-created_at'], name='messaging_v_convers_6bf8a4_idx'),
        ),
        migrations.AddIndex(
            model_name='videocall',
            index=models.Index(fields=['caller', '-created_at'], name='messaging_v_caller__8fe093_idx'),
        ),
        migrations.AddIndex(
            model_name='videocall',
            index=models.Index(fields=['status', '-created_at'], name='messaging_v_status_bf7f33_idx'),
        ),
        migrations.AddIndex(
            model_name='callsignal',
            index=models.Index(fields=['call', 'signal_type', '-created_at'], name='messaging_c_call_id_3501d6_idx'),
        ),
        migrations.AddIndex(
            model_name='callsignal',
            index=models.Index(fields=['to_user', 'processed', '-created_at'], name='messaging_c_to_user_e1eb46_idx'),
        ),
        migrations.AddIndex(
            model_name='callparticipant',
            index=models.Index(fields=['call', 'status'], name='messaging_c_call_id_3b8545_idx'),
        ),
        migrations.AddIndex(
            model_name='callparticipant',
            index=models.Index(fields=['user', '-invited_at'], name='messaging_c_user_id_975f39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='callparticipant',
            unique_together={('call', 'user')},
        ),
    ]
