# Generated by Django 5.2.1 on 2025-07-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_add_video_call_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
