# Generated by Django 5.2.4 on 2025-08-22 10:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CofounderMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(default=list)),
                ('experience_years', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('commitment_level', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('advisory', 'Advisory')], max_length=20)),
                ('equity_expectation', models.CharField(blank=True, max_length=50)),
                ('looking_for_skills', models.JSONField(default=list)),
                ('startup_stage_preference', models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'MVP Stage'), ('revenue', 'Revenue Stage'), ('growth', 'Growth Stage')], max_length=20)),
                ('bio', models.TextField()),
                ('achievements', models.TextField(blank=True)),
                ('ideal_cofounder', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('meetup', 'Meetup'), ('workshop', 'Workshop'), ('pitch', 'Pitch Event'), ('networking', 'Networking'), ('webinar', 'Webinar')], max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_online', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('meeting_url', models.URLField(blank=True)),
                ('requires_registration', models.BooleanField(default=True)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('waitlisted', 'Waitlisted'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('registration_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skills_complementarity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('interest_alignment', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('experience_balance', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('follow', 'New Follower'), ('mention', 'Mentioned in Post'), ('comment', 'Comment on Your Post'), ('reply', 'Reply to Your Comment'), ('like', 'Post Liked'), ('event_reminder', 'Event Reminder'), ('space_invite', 'Space Invitation'), ('cofounder_match', 'Potential Co-founder Match')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('post_id', models.UUIDField(blank=True, null=True)),
                ('comment_id', models.UUIDField(blank=True, null=True)),
                ('space_id', models.UUIDField(blank=True, null=True)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('pitch_deck', 'Pitch Deck'), ('business_plan', 'Business Plan'), ('legal', 'Legal Documents'), ('marketing', 'Marketing Materials'), ('financial', 'Financial Models'), ('email', 'Email Templates')], max_length=50)),
                ('content', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('preview_image_url', models.URLField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('is_premium', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-download_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='👥', max_length=10)),
                ('cover_image_url', models.URLField(blank=True)),
                ('space_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('invite_only', 'Invite Only')], default='public', max_length=20)),
                ('auto_approve_members', models.BooleanField(default=True)),
                ('allow_member_posts', models.BooleanField(default=True)),
                ('require_post_approval', models.BooleanField(default=False)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-member_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='member', max_length=20)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('banned_reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, help_text='Profile picture URL')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('expertise', models.JSONField(default=list)),
                ('looking_for', models.JSONField(default=list)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=50)),
                ('github_username', models.CharField(blank=True, max_length=50)),
                ('personal_website', models.URLField(blank=True)),
                ('is_open_to_opportunities', models.BooleanField(default=True)),
                ('preferred_contact_method', models.CharField(choices=[('platform', 'Platform Messages'), ('email', 'Email'), ('linkedin', 'LinkedIn')], default='platform', max_length=20)),
                ('reputation_score', models.IntegerField(default=0)),
                ('helpful_votes', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('badges', models.JSONField(default=list)),
                ('show_online_status', models.BooleanField(default=True)),
                ('allow_direct_messages', models.BooleanField(default=True)),
                ('email_on_mention', models.BooleanField(default=True)),
                ('email_on_reply', models.BooleanField(default=True)),
                ('email_on_follow', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
