# Generated by Django 5.2.4 on 2025-08-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connect', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofoundermatch',
            name='industry_preferences',
            field=models.ManyToManyField(blank=True, to='startups.industry'),
        ),
    ]
