# Generated by Django 5.2.4 on 2025-08-22 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connect', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cofoundermatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofounder_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='connect.event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcetemplate',
            name='contributed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='space',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='space',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='connect.space'),
        ),
        migrations.AddField(
            model_name='spacemembership',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='connect.space'),
        ),
        migrations.AddField(
            model_name='spacemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connect_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cofoundermatch',
            index=models.Index(fields=['is_active', '-created_at'], name='connect_cof_is_acti_3a2753_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'status'], name='connect_eve_event_i_ec34c6_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user', '-registered_at'], name='connect_eve_user_id_45399e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', '-created_at'], name='connect_fol_followe_53e808_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following', '-created_at'], name='connect_fol_followi_b3caaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AddIndex(
            model_name='matchscore',
            index=models.Index(fields=['-overall_score'], name='connect_mat_overall_125ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='matchscore',
            index=models.Index(fields=['user1', '-overall_score'], name='connect_mat_user1_i_6bc3e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchscore',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='connect_not_user_id_35316c_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcetemplate',
            index=models.Index(fields=['category', '-download_count'], name='connect_res_categor_e6fd9c_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['-member_count'], name='connect_spa_member__d38a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['slug'], name='connect_spa_slug_ed03fc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime', 'is_published'], name='connect_eve_start_d_7ceb18_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['host', '-created_at'], name='connect_eve_host_id_2d20bb_idx'),
        ),
        migrations.AddIndex(
            model_name='spacemembership',
            index=models.Index(fields=['user', '-joined_at'], name='connect_spa_user_id_165404_idx'),
        ),
        migrations.AddIndex(
            model_name='spacemembership',
            index=models.Index(fields=['space', 'role'], name='connect_spa_space_i_128e46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spacemembership',
            unique_together={('space', 'user')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-reputation_score'], name='connect_use_reputat_b5bae7_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-last_seen'], name='connect_use_last_se_5311f6_idx'),
        ),
    ]
