# Generated by Django 5.2.1 on 2025-07-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
