# Generated by Django 5.2.1 on 2025-07-21 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_expired_status'),
        ('users', '0006_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='selected_resume',
            field=models.ForeignKey(blank=True, help_text="Resume selected from user's saved resumes", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='users.resume'),
        ),
    ]
