# Generated by Django 5.2.1 on 2025-07-12 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_like', models.BooleanField(default=True)),
                ('email_on_comment', models.BooleanField(default=True)),
                ('email_on_follow', models.BooleanField(default=True)),
                ('email_on_mention', models.BooleanField(default=True)),
                ('email_on_job_application', models.BooleanField(default=True)),
                ('email_on_approval', models.BooleanField(default=True)),
                ('push_on_like', models.BooleanField(default=True)),
                ('push_on_comment', models.BooleanField(default=True)),
                ('push_on_follow', models.BooleanField(default=True)),
                ('push_on_mention', models.BooleanField(default=True)),
                ('push_on_job_application', models.BooleanField(default=False)),
                ('push_on_approval', models.BooleanField(default=True)),
                ('inapp_on_like', models.BooleanField(default=True)),
                ('inapp_on_comment', models.BooleanField(default=True)),
                ('inapp_on_follow', models.BooleanField(default=True)),
                ('inapp_on_mention', models.BooleanField(default=True)),
                ('inapp_on_job_application', models.BooleanField(default=True)),
                ('inapp_on_approval', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like_startup', 'Startup Liked'), ('comment_startup', 'Startup Comment'), ('rating_startup', 'Startup Rating'), ('like_post', 'Post Liked'), ('comment_post', 'Post Comment'), ('job_application', 'Job Application'), ('startup_approved', 'Startup Approved'), ('startup_rejected', 'Startup Rejected'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('claim_approved', 'Claim Approved'), ('claim_rejected', 'Claim Rejected'), ('follow_user', 'User Follow'), ('mention', 'Mention'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('startup_id', models.PositiveIntegerField(blank=True, null=True)),
                ('post_id', models.PositiveIntegerField(blank=True, null=True)),
                ('job_id', models.PositiveIntegerField(blank=True, null=True)),
                ('comment_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx'), models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_028906_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
