# Generated by Django 5.2.1 on 2025-07-13 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRankingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_score', models.FloatField(default=0.0)),
                ('recency_score', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(default=0.0)),
                ('author_reputation_score', models.FloatField(default=0.0)),
                ('trending_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(db_index=True, default=0.0)),
                ('personalization_data', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_score', to='posts.post')),
            ],
            options={
                'indexes': [models.Index(fields=['-total_score', '-calculated_at'], name='posts_postr_total_s_134fac_idx'), models.Index(fields=['-engagement_score'], name='posts_postr_engagem_aeff1c_idx'), models.Index(fields=['-trending_score'], name='posts_postr_trendin_3ca6c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('bookmark', 'Bookmark'), ('click_profile', 'Click Profile'), ('click_link', 'Click Link'), ('time_spent', 'Time Spent Reading')], max_length=20)),
                ('value', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='posts_useri_user_id_e46dae_idx'), models.Index(fields=['post', 'interaction_type', '-created_at'], name='posts_useri_post_id_8bb12a_idx'), models.Index(fields=['user', 'interaction_type', '-created_at'], name='posts_useri_user_id_1b6935_idx')],
            },
        ),
    ]
