# Generated by Django 5.2.1 on 2025-07-15 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_add_ranking_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('view_duration', models.FloatField(blank=True, null=True)),
                ('viewed_from', models.CharField(blank=True, max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-seen_at'], name='posts_seenp_user_id_48e617_idx'), models.Index(fields=['post', '-seen_at'], name='posts_seenp_post_id_89afbd_idx'), models.Index(fields=['user', 'post'], name='posts_seenp_user_id_813ea8_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
