# Generated by Django 5.2.1 on 2025-07-16 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_seenpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add 'poll' to Post.POST_TYPES choices
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('question', 'Question'), ('announcement', 'Announcement'), ('resource', 'Resource'), ('event', 'Event'), ('poll', 'Poll')], default='discussion', max_length=20),
        ),
        
        # Create Poll model
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiple_choice', models.BooleanField(default=False)),
                ('max_selections', models.PositiveSmallIntegerField(default=1)),
                ('anonymous_voting', models.BooleanField(default=False)),
                ('show_results_before_vote', models.BooleanField(default=False)),
                ('allow_result_view_without_vote', models.BooleanField(default=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='posts.post')),
            ],
        ),
        
        # Create PollOption model
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='posts.poll')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        
        # Create PollVote model
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
        # Add indexes
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['ends_at'], name='posts_poll_ends_at_idx'),
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['poll', 'order'], name='posts_polloption_poll_order_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['poll', 'user'], name='posts_pollvote_poll_user_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['option', '-voted_at'], name='posts_pollvote_option_voted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['user', '-voted_at'], name='posts_pollvote_user_voted_at_idx'),
        ),
    ]
