# Generated by Django 5.2.1 on 2025-07-16 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20250716_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlink',
            name='fetched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
