# Generated by Django 5.2.1 on 2025-07-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20250716_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_solution',
            field=models.BooleanField(default=False),
        ),
    ]
