# Generated by Django 5.2.1 on 2025-07-17 05:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20250716_1139'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlink',
            options={'ordering': ['fetched_at']},
        ),
        migrations.RenameIndex(
            model_name='poll',
            new_name='posts_poll_ends_at_60526b_idx',
            old_name='posts_poll_ends_at_idx',
        ),
        migrations.RenameIndex(
            model_name='polloption',
            new_name='posts_pollo_poll_id_b000b9_idx',
            old_name='posts_polloption_poll_order_idx',
        ),
        migrations.RenameIndex(
            model_name='pollvote',
            new_name='posts_pollv_poll_id_6e53d9_idx',
            old_name='posts_pollvote_poll_user_idx',
        ),
        migrations.RenameIndex(
            model_name='pollvote',
            new_name='posts_pollv_option__a7a6f1_idx',
            old_name='posts_pollvote_option_voted_at_idx',
        ),
        migrations.RenameIndex(
            model_name='pollvote',
            new_name='posts_pollv_user_id_6f957c_idx',
            old_name='posts_pollvote_user_voted_at_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_flagged',
        ),
        migrations.RemoveField(
            model_name='commentreaction',
            name='is_like',
        ),
        migrations.RemoveField(
            model_name='postbookmark',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='postlink',
            name='created_at',
        ),
        migrations.AddField(
            model_name='postbookmark',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postview',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='posts/images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='fetched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postshare',
            name='platform',
            field=models.CharField(choices=[('copy_link', 'Copy Link'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='postview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='postbookmark',
            index=models.Index(fields=['user', '-created_at'], name='posts_postb_user_id_b78223_idx'),
        ),
    ]
