# Generated by Django 5.2.4 on 2025-08-22 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, help_text='Admin user assigned to handle this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_post_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(help_text='Post being reported', on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to='posts.post'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='reporter',
            field=models.ForeignKey(help_text='User who submitted the report', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_post_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportaction',
            name='admin',
            field=models.ForeignKey(help_text='Admin who performed this action', on_delete=django.db.models.deletion.CASCADE, related_name='report_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reportstatistics',
            index=models.Index(fields=['date'], name='reports_rep_date_f06b94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportstatistics',
            unique_together={('date',)},
        ),
        migrations.AddField(
            model_name='userban',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userban',
            name='lifted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userban',
            name='post_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans', to='reports.postreport'),
        ),
        migrations.AddField(
            model_name='userban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, help_text='Admin user assigned to handle this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reported_user',
            field=models.ForeignKey(help_text='User being reported', on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reporter',
            field=models.ForeignKey(help_text='User who submitted the report', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userban',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans', to='reports.userreport'),
        ),
        migrations.AddField(
            model_name='reportaction',
            name='report',
            field=models.ForeignKey(help_text='The report this action is related to', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='reports.userreport'),
        ),
        migrations.AddField(
            model_name='userwarning',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_warnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userwarning',
            name='post_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='reports.postreport'),
        ),
        migrations.AddField(
            model_name='userwarning',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='reports.userreport'),
        ),
        migrations.AddField(
            model_name='userwarning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='postreport',
            index=models.Index(fields=['status', 'priority'], name='reports_pos_status_f8143e_idx'),
        ),
        migrations.AddIndex(
            model_name='postreport',
            index=models.Index(fields=['post', 'created_at'], name='reports_pos_post_id_3decb8_idx'),
        ),
        migrations.AddIndex(
            model_name='postreport',
            index=models.Index(fields=['reporter', 'created_at'], name='reports_pos_reporte_53e504_idx'),
        ),
        migrations.AddIndex(
            model_name='postreport',
            index=models.Index(fields=['assigned_admin', 'status'], name='reports_pos_assigne_59bd2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postreport',
            unique_together={('reporter', 'post')},
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['status', 'priority'], name='reports_use_status_6dd266_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reported_user', 'created_at'], name='reports_use_reporte_398652_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['reporter', 'created_at'], name='reports_use_reporte_b70008_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['assigned_admin', 'status'], name='reports_use_assigne_480a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['user', 'is_active'], name='reports_use_user_id_201c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['admin', '-created_at'], name='reports_use_admin_i_0c9ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['expires_at'], name='reports_use_expires_54e67e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportaction',
            index=models.Index(fields=['report', 'created_at'], name='reports_rep_report__3c502f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportaction',
            index=models.Index(fields=['admin', 'created_at'], name='reports_rep_admin_i_aa2bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportaction',
            index=models.Index(fields=['action_type', 'created_at'], name='reports_rep_action__802302_idx'),
        ),
        migrations.AddIndex(
            model_name='userwarning',
            index=models.Index(fields=['user', '-created_at'], name='reports_use_user_id_0dcc06_idx'),
        ),
        migrations.AddIndex(
            model_name='userwarning',
            index=models.Index(fields=['admin', '-created_at'], name='reports_use_admin_i_a088a2_idx'),
        ),
    ]
