# Generated by Django 5.2.1 on 2025-07-12 08:15

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 3-20 characters. Letters, numbers, underscores and dots only.', max_length=20, unique=True, validators=[apps.users.models.validate_username]),
        ),
    ]
