# Generated by Django 5.2.1 on 2025-07-21 05:08

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_stripe_customer_id_user_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Give your resume a descriptive title (e.g., 'Software Engineer Resume', 'Marketing Resume')", max_length=100)),
                ('file', models.FileField(help_text='Upload your resume (PDF, DOC, DOCX)', upload_to=apps.users.models.user_resume_upload_path)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default resume for job applications')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-uploaded_at'],
                'indexes': [models.Index(fields=['user', '-uploaded_at'], name='users_resum_user_id_8ccfbc_idx'), models.Index(fields=['user', 'is_default'], name='users_resum_user_id_fc6e4f_idx')],
            },
        ),
    ]
