# Generated by Django 4.2.23 on 2025-07-29 11:42

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Your first name. Only letters, spaces, hyphens, and apostrophes allowed.', max_length=30, validators=[apps.users.models.validate_first_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Your last name. Only letters, spaces, hyphens, and apostrophes allowed.', max_length=30, validators=[apps.users.models.validate_last_name]),
        ),
    ]
