# Generated by Django 4.2.23 on 2025-07-30 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_follower_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('lifetime_points', models.PositiveIntegerField(default=0)),
                ('points_this_month', models.PositiveIntegerField(default=0)),
                ('points_this_week', models.PositiveIntegerField(default=0)),
                ('achievement_points', models.PositiveIntegerField(default=0)),
                ('content_points', models.PositiveIntegerField(default=0)),
                ('social_points', models.PositiveIntegerField(default=0)),
                ('startup_points', models.PositiveIntegerField(default=0)),
                ('job_points', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_weekly_reset', models.DateTimeField(auto_now_add=True)),
                ('last_monthly_reset', models.DateTimeField(auto_now_add=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('level_progress', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['-total_points'], name='users_userp_total_p_b0e677_idx'), models.Index(fields=['-lifetime_points'], name='users_userp_lifetim_9b6131_idx'), models.Index(fields=['level', '-total_points'], name='users_userp_level_6beb15_idx')],
            },
        ),
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(choices=[('achievement', 'Achievement Unlocked'), ('post_create', 'Created Post'), ('story_create', 'Created Story'), ('startup_submit', 'Submitted Startup'), ('startup_claim', 'Claimed Startup'), ('job_post', 'Posted Job'), ('job_apply', 'Applied for Job'), ('follow_user', 'Followed User'), ('profile_complete', 'Profile Completed'), ('daily_login', 'Daily Login'), ('weekly_bonus', 'Weekly Activity Bonus'), ('monthly_bonus', 'Monthly Activity Bonus'), ('referral', 'Referred New User'), ('other', 'Other Activity')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('post_id', models.UUIDField(blank=True, null=True)),
                ('startup_id', models.UUIDField(blank=True, null=True)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_point_user_id_3e8d18_idx'), models.Index(fields=['reason', '-created_at'], name='users_point_reason_f0a7ac_idx')],
            },
        ),
    ]
