# Generated by Django 4.2.23 on 2025-07-30 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userpoints_pointshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointshistory',
            name='reason',
            field=models.CharField(choices=[('achievement', 'Achievement Unlocked'), ('post_create', 'Created Post'), ('story_create', 'Created Story'), ('startup_submit', 'Submitted Startup'), ('startup_claim', 'Claimed Startup'), ('job_post', 'Posted Job'), ('job_apply', 'Applied for Job'), ('follow_user', 'Followed User'), ('profile_complete', 'Profile Completed'), ('daily_login', 'Daily Login'), ('weekly_bonus', 'Weekly Activity Bonus'), ('monthly_bonus', 'Monthly Activity Bonus'), ('referral', 'Referred New User'), ('signup_bonus', 'Welcome Bonus'), ('first_post', 'First Post Bonus'), ('login_streak_7', 'Weekly Login Streak'), ('login_streak_30', 'Monthly Login Streak'), ('other', 'Other Activity')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserLoginStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('total_login_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-current_streak'], name='users_userl_user_id_0a115f_idx'), models.Index(fields=['-longest_streak'], name='users_userl_longest_2e02bd_idx')],
            },
        ),
    ]
