# Generated by Django 4.2.23 on 2025-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_pointshistory_reason_userloginstreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointshistory',
            name='reason',
            field=models.CharField(choices=[('achievement', 'Achievement Unlocked'), ('signup_bonus', 'Welcome Bonus'), ('email_verify', 'Email Verified'), ('phone_verify', 'Phone Verified'), ('profile_picture_upload', 'Profile Picture Added'), ('profile_bio_complete', 'Bio Added'), ('profile_location_add', 'Location Added'), ('profile_website_add', 'Website Added'), ('profile_complete', 'Profile Completed'), ('first_interests_select', 'Interests Selected'), ('daily_login', 'Daily Login'), ('login_streak_3', '3-Day Login Streak'), ('login_streak_7', '7-Day Login Streak'), ('login_streak_30', '30-Day Login Streak'), ('first_session', 'First Platform Visit'), ('first_post', 'First Post Created'), ('post_create', 'Post Created'), ('post_with_image', 'Post with Image'), ('post_with_video', 'Post with Video'), ('first_story', 'First Story Created'), ('story_create', 'Story Created'), ('story_with_media', 'Story with Media'), ('comment_create', 'Comment Added'), ('first_comment', 'First Comment'), ('first_startup_submit', 'First Startup Submitted'), ('startup_submit', 'Startup Submitted'), ('startup_claim', 'Startup Claimed'), ('startup_verify', 'Startup Verified'), ('startup_update', 'Startup Updated'), ('startup_logo_upload', 'Startup Logo Added'), ('first_job_post', 'First Job Posted'), ('job_post', 'Job Posted'), ('job_apply', 'Applied for Job'), ('job_bookmark', 'Job Bookmarked'), ('resume_upload', 'Resume Uploaded'), ('resume_update', 'Resume Updated'), ('first_follow', 'First User Followed'), ('follow_user', 'User Followed'), ('get_followed', 'Gained Follower'), ('like_post', 'Post Liked'), ('share_post', 'Post Shared'), ('bookmark_post', 'Post Bookmarked'), ('join_community', 'Community Joined'), ('message_send', 'Message Sent'), ('first_message', 'First Message Sent'), ('milestone_10_posts', '10 Posts Milestone'), ('milestone_50_posts', '50 Posts Milestone'), ('milestone_100_followers', '100 Followers Milestone'), ('milestone_verified', 'Account Verified'), ('weekly_bonus', 'Weekly Activity Bonus'), ('monthly_bonus', 'Monthly Activity Bonus'), ('referral', 'User Referred'), ('early_adopter', 'Early Adopter Bonus'), ('beta_tester', 'Beta Tester Bonus'), ('feedback_submit', 'Feedback Submitted'), ('bug_report', 'Bug Reported'), ('posting_streak_7', '7-Day Posting Streak'), ('posting_streak_30', '30-Day Posting Streak'), ('engagement_streak_7', '7-Day Engagement Streak'), ('platform_anniversary', 'Platform Anniversary'), ('quality_content', 'Quality Content'), ('helpful_comment', 'Helpful Comment'), ('mentor_activity', 'Mentoring Activity'), ('event_participation', 'Event Participation'), ('survey_complete', 'Survey Completed'), ('other', 'Other Activity')], max_length=30),
        ),
    ]
