# Generated by Django 4.2.23 on 2025-08-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_pointshistory_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='video_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object containing video editing settings like trim, filters, overlays'),
        ),
    ]
