# Generated by Django 4.2.23 on 2025-08-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_story_video_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object containing image editing settings like filters, transforms, overlays'),
        ),
    ]
