# Generated by Django 5.2.4 on 2025-08-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like_startup', 'Startup Liked'), ('comment_startup', 'Startup Comment'), ('rating_startup', 'Startup Rating'), ('like_post', 'Post Liked'), ('comment_post', 'Post Comment'), ('job_application', 'Job Application'), ('startup_approved', 'Startup Approved'), ('startup_rejected', 'Startup Rejected'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('claim_approved', 'Claim Approved'), ('claim_rejected', 'Claim Rejected'), ('follow_user', 'User Follow'), ('mention', 'Mention'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('startup_id', models.PositiveIntegerField(blank=True, null=True)),
                ('post_id', models.PositiveIntegerField(blank=True, null=True)),
                ('job_id', models.PositiveIntegerField(blank=True, null=True)),
                ('comment_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_like', models.BooleanField(default=True)),
                ('email_on_comment', models.BooleanField(default=True)),
                ('email_on_follow', models.BooleanField(default=True)),
                ('email_on_mention', models.BooleanField(default=True)),
                ('email_on_job_application', models.BooleanField(default=True)),
                ('email_on_approval', models.BooleanField(default=True)),
                ('push_on_like', models.BooleanField(default=True)),
                ('push_on_comment', models.BooleanField(default=True)),
                ('push_on_follow', models.BooleanField(default=True)),
                ('push_on_mention', models.BooleanField(default=True)),
                ('push_on_job_application', models.BooleanField(default=False)),
                ('push_on_approval', models.BooleanField(default=True)),
                ('inapp_on_like', models.BooleanField(default=True)),
                ('inapp_on_comment', models.BooleanField(default=True)),
                ('inapp_on_follow', models.BooleanField(default=True)),
                ('inapp_on_mention', models.BooleanField(default=True)),
                ('inapp_on_job_application', models.BooleanField(default=True)),
                ('inapp_on_approval', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
